/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package lab1proyectofinal.vistas;

import java.awt.Color;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import lab1proyectofinal.accesoADatos.BrigadaData;
import lab1proyectofinal.accesoADatos.Utils;
import lab1proyectofinal.entidades.Bombero;
import lab1proyectofinal.entidades.Brigada;

/**
 *
 * @author nahue
 */
public class BrigadasSegunSituacion extends javax.swing.JInternalFrame {

    private final BrigadaData brigadaData;
    private List<Brigada> brigadas;
    private DefaultTableModel modeloTablaBrigadasAsignables = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int i, int i1) {
            return false;
        }
    };
    private DefaultTableModel modeloTablaBrigadasAtendiendoEmerg = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int i, int i1) {
            return false;
        }
    };
    private DefaultTableModel modeloTablaBrigadasIncompletas = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int i, int i1) {
            return false;
        }
    };

    public BrigadasSegunSituacion(BrigadaData brigadaData) {
        initComponents();
        this.brigadaData = brigadaData;
        armarCabecera(jTableBrigadasAsignables, modeloTablaBrigadasAsignables);
        armarCabecera(jTableBrigadasAtendiendoEmerg, modeloTablaBrigadasAtendiendoEmerg);
        armarCabecera(jTableBrigadasIncompletas, modeloTablaBrigadasIncompletas);
    }

    private void armarCabecera(JTable jTable, DefaultTableModel dtm) {
        jTable.getTableHeader().setFont(Utils.fuenteNegrita);
        dtm.addColumn("Nombre");
        dtm.addColumn("Especialidad");
        dtm.addColumn("Disponible");
        dtm.addColumn("Cuartel");
        jTable.setModel(dtm);
        jTable.getColumnModel().getColumn(0).setPreferredWidth(70);
        jTable.getColumnModel().getColumn(1).setPreferredWidth(250);
        jTable.getColumnModel().getColumn(2).setPreferredWidth(5);
    }

    private void cargarDatosTablaAsignables() {
        brigadas = brigadaData.listarBrigadasAsignables();
        modeloTablaBrigadasAsignables.setRowCount(0);
        if (brigadas.isEmpty()) {
            jLabelMensajeTablaAsignables.setForeground(Color.BLACK);
            jLabelMensajeTablaAsignables.setText("Actualmente no hay ninguna brigada asignable.");
        } else {
            for (Brigada bri : brigadas) {
                modeloTablaBrigadasAsignables.addRow(new Object[]{bri.getNombreBrigada(),
                    bri.getEspecialidad(), bri.isDisponible() ? "Si" : "No ",
                    bri.getCuartel().getNombreCuartel()});
            }
            jLabelMensajeTablaAsignables.setText("");
        }
    }

    private void cargarDatosTablaAtendiendoEmerg() {
        brigadas = brigadaData.listarBrigadasAtendiendoEmergencia();
        modeloTablaBrigadasAtendiendoEmerg.setRowCount(0);
        if (brigadas.isEmpty()) {
            jLabelMensajeTablaAtendiendoEmerg.setForeground(Color.BLACK);
            jLabelMensajeTablaAtendiendoEmerg.setText("Actualmente no hay ninguna brigada "
                    + "atendiendo una emergencia.");
        } else {
            for (Brigada bri : brigadas) {
                modeloTablaBrigadasAtendiendoEmerg.addRow(new Object[]{bri.getNombreBrigada(),
                    bri.getEspecialidad(), bri.isDisponible() ? "Si" : "No ",
                    bri.getCuartel().getNombreCuartel()});
            }
            jLabelMensajeTablaAtendiendoEmerg.setText("");
        }
    }

    private void cargarDatosTablaIncompletas() {
        brigadas = brigadaData.listarBrigadasIncompletas();
        modeloTablaBrigadasIncompletas.setRowCount(0);
        if (brigadas.isEmpty()) {
            jLabelMensajeTablaIncompletas.setForeground(Color.BLACK);
            jLabelMensajeTablaIncompletas.setText("Actualmente no hay ninguna brigada incompleta.");
        } else {
            for (Brigada bri : brigadas) {
                modeloTablaBrigadasIncompletas.addRow(new Object[]{bri.getNombreBrigada(),
                    bri.getEspecialidad(), bri.isDisponible() ? "Si" : "No ",
                    bri.getCuartel().getNombreCuartel()});
            }
            jLabelMensajeTablaIncompletas.setText("");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneTodosLosCuarteles = new javax.swing.JScrollPane();
        jTableBrigadasAsignables = new javax.swing.JTable();
        jLabelAsignables = new javax.swing.JLabel();
        jLabelTituloPrincipal = new javax.swing.JLabel();
        jLabelMensajeTablaAsignables = new javax.swing.JLabel();
        jButtonSalir = new javax.swing.JButton();
        jScrollPaneTodosLosCuarteles1 = new javax.swing.JScrollPane();
        jTableBrigadasAtendiendoEmerg = new javax.swing.JTable();
        jLabelAtendiendoEmerg = new javax.swing.JLabel();
        jLabelMensajeTablaAtendiendoEmerg = new javax.swing.JLabel();
        jScrollPaneTodosLosCuarteles2 = new javax.swing.JScrollPane();
        jTableBrigadasIncompletas = new javax.swing.JTable();
        jLabelIncompletas = new javax.swing.JLabel();
        jLabelMensajeTablaIncompletas = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1140, 765));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableBrigadasAsignables.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTableBrigadasAsignables.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        jTableBrigadasAsignables.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableBrigadasAsignables.getTableHeader().setResizingAllowed(false);
        jTableBrigadasAsignables.getTableHeader().setReorderingAllowed(false);
        jScrollPaneTodosLosCuarteles.setViewportView(jTableBrigadasAsignables);

        getContentPane().add(jScrollPaneTodosLosCuarteles, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 940, 130));

        jLabelAsignables.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelAsignables.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAsignables.setText("Asignables");
        getContentPane().add(jLabelAsignables, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 940, -1));

        jLabelTituloPrincipal.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelTituloPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloPrincipal.setText("Brigadas según su situación");
        getContentPane().add(jLabelTituloPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 940, -1));

        jLabelMensajeTablaAsignables.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        getContentPane().add(jLabelMensajeTablaAsignables, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 920, 20));

        jButtonSalir.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 680, -1, -1));

        jTableBrigadasAtendiendoEmerg.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTableBrigadasAtendiendoEmerg.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        jTableBrigadasAtendiendoEmerg.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableBrigadasAtendiendoEmerg.getTableHeader().setResizingAllowed(false);
        jTableBrigadasAtendiendoEmerg.getTableHeader().setReorderingAllowed(false);
        jScrollPaneTodosLosCuarteles1.setViewportView(jTableBrigadasAtendiendoEmerg);

        getContentPane().add(jScrollPaneTodosLosCuarteles1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 940, 130));

        jLabelAtendiendoEmerg.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelAtendiendoEmerg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAtendiendoEmerg.setText("Atendiendo una emergencia");
        getContentPane().add(jLabelAtendiendoEmerg, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 940, -1));

        jLabelMensajeTablaAtendiendoEmerg.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        getContentPane().add(jLabelMensajeTablaAtendiendoEmerg, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 115, 920, 20));

        jTableBrigadasIncompletas.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTableBrigadasIncompletas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        jTableBrigadasIncompletas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableBrigadasIncompletas.getTableHeader().setResizingAllowed(false);
        jTableBrigadasIncompletas.getTableHeader().setReorderingAllowed(false);
        jScrollPaneTodosLosCuarteles2.setViewportView(jTableBrigadasIncompletas);

        getContentPane().add(jScrollPaneTodosLosCuarteles2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 580, 940, 130));

        jLabelIncompletas.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelIncompletas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIncompletas.setText("Incompletas");
        getContentPane().add(jLabelIncompletas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 940, -1));

        jLabelMensajeTablaIncompletas.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        getContentPane().add(jLabelMensajeTablaIncompletas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 550, 920, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        this.hide();
        if (jTableBrigadasAsignables.getRowCount() > 0) {
            jTableBrigadasAsignables.removeRowSelectionInterval(0,
                    jTableBrigadasAsignables.getRowCount() - 1);
        }
        if (jTableBrigadasAtendiendoEmerg.getRowCount() > 0) {
            jTableBrigadasAtendiendoEmerg.removeRowSelectionInterval(0,
                    jTableBrigadasAtendiendoEmerg.getRowCount() - 1);
        }

        if (jTableBrigadasIncompletas.getRowCount() > 0) {
            jTableBrigadasIncompletas.removeRowSelectionInterval(0,
                    jTableBrigadasIncompletas.getRowCount() - 1);
        }
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        cargarDatosTablaAsignables();
        cargarDatosTablaAtendiendoEmerg();
        cargarDatosTablaIncompletas();
    }//GEN-LAST:event_formInternalFrameActivated


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelAsignables;
    private javax.swing.JLabel jLabelAtendiendoEmerg;
    private javax.swing.JLabel jLabelIncompletas;
    private javax.swing.JLabel jLabelMensajeTablaAsignables;
    private javax.swing.JLabel jLabelMensajeTablaAtendiendoEmerg;
    private javax.swing.JLabel jLabelMensajeTablaIncompletas;
    private javax.swing.JLabel jLabelTituloPrincipal;
    private javax.swing.JScrollPane jScrollPaneTodosLosCuarteles;
    private javax.swing.JScrollPane jScrollPaneTodosLosCuarteles1;
    private javax.swing.JScrollPane jScrollPaneTodosLosCuarteles2;
    private javax.swing.JTable jTableBrigadasAsignables;
    private javax.swing.JTable jTableBrigadasAtendiendoEmerg;
    private javax.swing.JTable jTableBrigadasIncompletas;
    // End of variables declaration//GEN-END:variables
}
