/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package lab1proyectofinal.vistas;

import java.awt.Color;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import lab1proyectofinal.accesoADatos.BrigadaData;
import lab1proyectofinal.accesoADatos.Utils;
import lab1proyectofinal.entidades.Brigada;

/**
 *
 * @author nahue
 */
public class BrigadasSegunSituacion extends javax.swing.JInternalFrame {

    private final BrigadaData brigadaData;
    private List<Brigada> listaBrigada;
    private DefaultTableModel modeloJTaAsignables = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int i, int i1) {
            return false;
        }
    };
    private DefaultTableModel modeloJTaAtendiendoEmerg = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int i, int i1) {
            return false;
        }
    };
    private DefaultTableModel modeloJTaIncompletas = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int i, int i1) {
            return false;
        }
    };

    public BrigadasSegunSituacion(BrigadaData brigadaData) {
        initComponents();
        this.brigadaData = brigadaData;
        configurarTablaBrigada(jTaAsignables, modeloJTaAsignables);
        configurarTablaBrigada(jTaAtendiendoEmerg, modeloJTaAtendiendoEmerg);
        configurarTablaBrigada(jTabIncompletas, modeloJTaIncompletas);
    }

    private void configurarTablaBrigada(JTable jTable, DefaultTableModel dtm) {
        jTable.getTableHeader().setFont(Utils.fuenteNegrita);
        dtm.addColumn("Nombre");
        dtm.addColumn("Especialidad");
        dtm.addColumn("EnServicio");
        dtm.addColumn("Cuartel");
        jTable.setModel(dtm);
        jTable.getColumnModel().getColumn(0).setPreferredWidth(70);
        jTable.getColumnModel().getColumn(1).setPreferredWidth(250);
        jTable.getColumnModel().getColumn(2).setPreferredWidth(5);

        jTable.setRowHeight(20);
    }

    private void cargarDatosJTaAsignables() {
        listaBrigada = brigadaData.listarBrigadasAsignables();
        modeloJTaAsignables.setRowCount(0);
        if (listaBrigada.isEmpty()) {
            jLabMensajeTaAsignables.setForeground(Color.BLACK);
            jLabMensajeTaAsignables.setText("Actualmente no hay ninguna brigada asignable.");
        } else {
            for (Brigada bri : listaBrigada) {
                modeloJTaAsignables.addRow(new Object[]{bri.getNombreBrigada(),
                    bri.getEspecialidad(), bri.isEnServicio() ? "Si" : "No ",
                    bri.getCuartel().getNombreCuartel()});
            }
            jLabMensajeTaAsignables.setText("");
        }
    }

    private void cargarDatosJTaAtendiendoEmerg() {
        listaBrigada = brigadaData.listarBrigadasAtendiendoEmergencia();
        modeloJTaAtendiendoEmerg.setRowCount(0);
        if (listaBrigada.isEmpty()) {
            jLabMensajeJTaAtendiendoEmerg.setForeground(Color.BLACK);
            jLabMensajeJTaAtendiendoEmerg.setText("Actualmente no hay ninguna brigada "
                    + "atendiendo una emergencia.");
        } else {
            for (Brigada bri : listaBrigada) {
                modeloJTaAtendiendoEmerg.addRow(new Object[]{bri.getNombreBrigada(),
                    bri.getEspecialidad(), bri.isEnServicio() ? "Si" : "No ",
                    bri.getCuartel().getNombreCuartel()});
            }
            jLabMensajeJTaAtendiendoEmerg.setText("");
        }
    }

    private void cargarDatosJTaIncompletas() {
        listaBrigada = brigadaData.listarBrigadasIncompletas();
        modeloJTaIncompletas.setRowCount(0);
        if (listaBrigada.isEmpty()) {
            jLabMensajeTaIncompletas.setForeground(Color.BLACK);
            jLabMensajeTaIncompletas.setText("Actualmente no hay ninguna brigada incompleta.");
        } else {
            for (Brigada bri : listaBrigada) {
                modeloJTaIncompletas.addRow(new Object[]{bri.getNombreBrigada(),
                    bri.getEspecialidad(), bri.isEnServicio() ? "Si" : "No ",
                    bri.getCuartel().getNombreCuartel()});
            }
            jLabMensajeTaIncompletas.setText("");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneTodosLosCuarteles = new javax.swing.JScrollPane();
        jTaAsignables = new javax.swing.JTable();
        jLabAsignables = new javax.swing.JLabel();
        jLabBrigadasSegunSituacion = new javax.swing.JLabel();
        jLabMensajeTaAsignables = new javax.swing.JLabel();
        jButtonSalir = new javax.swing.JButton();
        jScrollPaneTodosLosCuarteles1 = new javax.swing.JScrollPane();
        jTaAtendiendoEmerg = new javax.swing.JTable();
        jLabAtendiendoEmerg = new javax.swing.JLabel();
        jLabMensajeJTaAtendiendoEmerg = new javax.swing.JLabel();
        jScrollPaneTodosLosCuarteles2 = new javax.swing.JScrollPane();
        jTabIncompletas = new javax.swing.JTable();
        jLabIncompletas = new javax.swing.JLabel();
        jLabMensajeTaIncompletas = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1140, 765));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameDeactivated(evt);
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTaAsignables.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTaAsignables.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        jTaAsignables.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTaAsignables.getTableHeader().setResizingAllowed(false);
        jTaAsignables.getTableHeader().setReorderingAllowed(false);
        jScrollPaneTodosLosCuarteles.setViewportView(jTaAsignables);

        getContentPane().add(jScrollPaneTodosLosCuarteles, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 940, 130));

        jLabAsignables.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabAsignables.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabAsignables.setText("Asignables");
        getContentPane().add(jLabAsignables, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 940, -1));

        jLabBrigadasSegunSituacion.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabBrigadasSegunSituacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabBrigadasSegunSituacion.setText("Brigadas según su situación");
        getContentPane().add(jLabBrigadasSegunSituacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 940, -1));

        jLabMensajeTaAsignables.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        getContentPane().add(jLabMensajeTaAsignables, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 920, 20));

        jButtonSalir.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 680, -1, -1));

        jTaAtendiendoEmerg.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTaAtendiendoEmerg.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        jTaAtendiendoEmerg.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTaAtendiendoEmerg.getTableHeader().setResizingAllowed(false);
        jTaAtendiendoEmerg.getTableHeader().setReorderingAllowed(false);
        jScrollPaneTodosLosCuarteles1.setViewportView(jTaAtendiendoEmerg);

        getContentPane().add(jScrollPaneTodosLosCuarteles1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 940, 130));

        jLabAtendiendoEmerg.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabAtendiendoEmerg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabAtendiendoEmerg.setText("Atendiendo una emergencia");
        getContentPane().add(jLabAtendiendoEmerg, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 940, -1));

        jLabMensajeJTaAtendiendoEmerg.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        getContentPane().add(jLabMensajeJTaAtendiendoEmerg, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 115, 920, 20));

        jTabIncompletas.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTabIncompletas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        jTabIncompletas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTabIncompletas.getTableHeader().setResizingAllowed(false);
        jTabIncompletas.getTableHeader().setReorderingAllowed(false);
        jScrollPaneTodosLosCuarteles2.setViewportView(jTabIncompletas);

        getContentPane().add(jScrollPaneTodosLosCuarteles2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 580, 940, 130));

        jLabIncompletas.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabIncompletas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabIncompletas.setText("Incompletas");
        getContentPane().add(jLabIncompletas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 940, -1));

        jLabMensajeTaIncompletas.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        getContentPane().add(jLabMensajeTaIncompletas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 550, 920, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        this.hide();
        if (jTaAsignables.getRowCount() > 0) {
            jTaAsignables.removeRowSelectionInterval(0,
                    jTaAsignables.getRowCount() - 1);
        }
        if (jTaAtendiendoEmerg.getRowCount() > 0) {
            jTaAtendiendoEmerg.removeRowSelectionInterval(0,
                    jTaAtendiendoEmerg.getRowCount() - 1);
        }

        if (jTabIncompletas.getRowCount() > 0) {
            jTabIncompletas.removeRowSelectionInterval(0,
                    jTabIncompletas.getRowCount() - 1);
        }
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        cargarDatosJTaAsignables();
        cargarDatosJTaAtendiendoEmerg();
        cargarDatosJTaIncompletas();
    }//GEN-LAST:event_formInternalFrameActivated

    private void formInternalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameDeactivated
        if (jTaAsignables.getRowCount() > 0) {
            jTaAsignables.removeRowSelectionInterval(0,
                    jTaAsignables.getRowCount() - 1);
        }
        if (jTaAtendiendoEmerg.getRowCount() > 0) {
            jTaAtendiendoEmerg.removeRowSelectionInterval(0,
                    jTaAtendiendoEmerg.getRowCount() - 1);
        }

        if (jTabIncompletas.getRowCount() > 0) {
            jTabIncompletas.removeRowSelectionInterval(0,
                    jTabIncompletas.getRowCount() - 1);
        }
    }//GEN-LAST:event_formInternalFrameDeactivated


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabAsignables;
    private javax.swing.JLabel jLabAtendiendoEmerg;
    private javax.swing.JLabel jLabBrigadasSegunSituacion;
    private javax.swing.JLabel jLabIncompletas;
    private javax.swing.JLabel jLabMensajeJTaAtendiendoEmerg;
    private javax.swing.JLabel jLabMensajeTaAsignables;
    private javax.swing.JLabel jLabMensajeTaIncompletas;
    private javax.swing.JScrollPane jScrollPaneTodosLosCuarteles;
    private javax.swing.JScrollPane jScrollPaneTodosLosCuarteles1;
    private javax.swing.JScrollPane jScrollPaneTodosLosCuarteles2;
    private javax.swing.JTable jTaAsignables;
    private javax.swing.JTable jTaAtendiendoEmerg;
    private javax.swing.JTable jTabIncompletas;
    // End of variables declaration//GEN-END:variables
}
