package lab1proyectofinal.vistas;

import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import lab1proyectofinal.accesoADatos.BomberoData;
import lab1proyectofinal.accesoADatos.BrigadaData;
import lab1proyectofinal.accesoADatos.CuartelData;
import lab1proyectofinal.accesoADatos.Utils;
import lab1proyectofinal.entidades.Bombero;
import lab1proyectofinal.entidades.Brigada;
import lab1proyectofinal.entidades.Cuartel;

/**
 *
 * @author Grupo-3
 */
public class FormularioBombero extends javax.swing.JInternalFrame {

    private final BomberoData bomberoData;
    private final BrigadaData brigadaData;
    private final CuartelData cuartelData;

    /**
     * Creates new form FormularioBombero
     */
    public FormularioBombero(CuartelData cuartelData, BrigadaData brigadaData, BomberoData bomberoData) {
        initComponents();
        this.cuartelData = cuartelData;
        this.brigadaData = brigadaData;
        this.bomberoData = bomberoData;
    }

    private void limpiarCampos() {
        dniTF.setText("");
        nombreTF.setText("");
        grupoSanguineoCB.setSelectedIndex(-1);
        fechaNacimientoDC.setCalendar(null);
        celularTF.setText("");
        cuartelCB.setSelectedIndex(-1);
        brigadaCB.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dniLabel = new javax.swing.JLabel();
        dniTF = new javax.swing.JTextField();
        nombreLabel = new javax.swing.JLabel();
        nombreTF = new javax.swing.JTextField();
        grupoSanguineoLabel = new javax.swing.JLabel();
        grupoSanguineoCB = new javax.swing.JComboBox<>();
        fechaNacimientoLabel = new javax.swing.JLabel();
        fechaNacimientoDC = new com.toedter.calendar.JDateChooser();
        celularLabel = new javax.swing.JLabel();
        celularTF = new javax.swing.JTextField();
        cuartelLabel = new javax.swing.JLabel();
        cuartelCB = new javax.swing.JComboBox<>();
        brigadaLabel = new javax.swing.JLabel();
        brigadaCB = new javax.swing.JComboBox<>();
        BtnComprobar = new javax.swing.JButton();
        BtnLimpiar = new javax.swing.JButton();
        BtnGuardar = new javax.swing.JButton();
        BtnSalir = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Formulario Bombero");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        dniLabel.setText("DNI:");

        nombreLabel.setText("Nombre Completo:");

        grupoSanguineoLabel.setText("Grupo Sanguíneo:");

        grupoSanguineoCB.setModel(new javax.swing.DefaultComboBoxModel<>(Utils.obtenerGrupoSanguineo()));

        fechaNacimientoLabel.setText("Fecha Nacimiento:");

        celularLabel.setText("Celular:");

        cuartelLabel.setText("Cuartel:");

        cuartelCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuartelCBActionPerformed(evt);
            }
        });

        brigadaLabel.setText("Brigada:");

        BtnComprobar.setText("Comprobar");
        BtnComprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnComprobarActionPerformed(evt);
            }
        });

        BtnLimpiar.setText("Limpiar Campos");
        BtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiarActionPerformed(evt);
            }
        });

        BtnGuardar.setText("Guardar");
        BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarActionPerformed(evt);
            }
        });

        BtnSalir.setText("Salir");
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreLabel)
                            .addComponent(dniLabel)
                            .addComponent(grupoSanguineoLabel)
                            .addComponent(fechaNacimientoLabel)
                            .addComponent(celularLabel)
                            .addComponent(cuartelLabel)
                            .addComponent(brigadaLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(celularTF, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fechaNacimientoDC, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(cuartelCB, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(brigadaCB, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nombreTF)
                            .addComponent(grupoSanguineoCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dniTF))
                        .addGap(18, 18, 18)
                        .addComponent(BtnComprobar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnLimpiar)
                        .addGap(18, 18, 18)
                        .addComponent(BtnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnSalir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dniLabel)
                    .addComponent(dniTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnComprobar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreLabel)
                    .addComponent(nombreTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(grupoSanguineoLabel)
                    .addComponent(grupoSanguineoCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fechaNacimientoLabel)
                    .addComponent(fechaNacimientoDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(celularLabel)
                    .addComponent(celularTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuartelLabel)
                    .addComponent(cuartelCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brigadaLabel)
                    .addComponent(brigadaCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnLimpiar)
                    .addComponent(BtnGuardar)
                    .addComponent(BtnSalir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        cuartelCB.removeAllItems();
        List<Cuartel> cuarteles = cuartelData.listarCuarteles();
        for (Cuartel cuartel : cuarteles) {
            cuartelCB.addItem(cuartel);
        }
        
        limpiarCampos();
    }//GEN-LAST:event_formInternalFrameActivated

    private void BtnComprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnComprobarActionPerformed
        String dniStr = dniTF.getText().trim();
        if (dniStr.isBlank()) {
            JOptionPane.showMessageDialog(this, "Ingrese el dni a comprobar.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int dni;
        try {
            dni = Integer.parseInt(dniStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Se esperaba un numero entero en DNI.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Bombero bombero = bomberoData.buscarBomberoPorDni(dni);
        if (bombero == null) {
            JOptionPane.showMessageDialog(this, "Esta persona puede registrarse.", "Disponible", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Este persona ya ha sido registrada anteriormente.", "No disponible", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_BtnComprobarActionPerformed

    private void BtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_BtnLimpiarActionPerformed

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
        String dniStr = dniTF.getText().trim();
        String nombreStr = nombreTF.getText().trim();
        String grupoSanguineoStr = (String) grupoSanguineoCB.getSelectedItem();
        Date date = fechaNacimientoDC.getDate();
        String celularStr = celularTF.getText().trim();
        Cuartel cuartel = (Cuartel) cuartelCB.getSelectedItem();
        Brigada brigada = (Brigada) brigadaCB.getSelectedItem();

        if (dniStr.isBlank() || nombreStr.isBlank() || grupoSanguineoStr == null
                || date == null || celularStr.isBlank() || cuartel == null
                || brigada == null) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int dni;
        try {
            dni = Integer.parseInt(dniStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Se esperaba un numero entero en DNI.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!Utils.esTelefonoValido(celularStr)) {
            JOptionPane.showMessageDialog(this, "Se esperaba un numero entero en Celular.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Este caso no deberia ocurrir nunca
        if (!cuartel.equals(brigada.getCuartel())) {
            JOptionPane.showMessageDialog(this, "La brigada no parece pertenecer al cuartel.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Obtener Local date del calendar
        LocalDate fechaNacimiento = date.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

        Bombero bombero = new Bombero(dni, nombreStr, grupoSanguineoStr, fechaNacimiento, celularStr, brigada);
        if (bomberoData.guardarBombero(bombero)) {
            JOptionPane.showMessageDialog(this, "Bombero guardado.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo guardar el bombero.\nQuizás ya haya un bombero guardado con este dni.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnGuardarActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        this.hide();
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void cuartelCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuartelCBActionPerformed
        brigadaCB.removeAllItems();
        brigadaCB.setEnabled(false);

        Cuartel cuartelSeleccionado = (Cuartel) cuartelCB.getSelectedItem();
        if (cuartelSeleccionado != null) {
            List<Brigada> brigadas = cuartelData.listarBrigadasEnCuartel(cuartelSeleccionado.getCodigoCuartel());
            for (Brigada brigada : brigadas) {
                brigadaCB.addItem(brigada);
            }
            brigadaCB.setSelectedIndex(-1);
            if (brigadaCB.getItemCount() > 0) {
                brigadaCB.setEnabled(true);
            }
        }
    }//GEN-LAST:event_cuartelCBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnComprobar;
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JButton BtnLimpiar;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JComboBox<Brigada> brigadaCB;
    private javax.swing.JLabel brigadaLabel;
    private javax.swing.JLabel celularLabel;
    private javax.swing.JTextField celularTF;
    private javax.swing.JComboBox<Cuartel> cuartelCB;
    private javax.swing.JLabel cuartelLabel;
    private javax.swing.JLabel dniLabel;
    private javax.swing.JTextField dniTF;
    private com.toedter.calendar.JDateChooser fechaNacimientoDC;
    private javax.swing.JLabel fechaNacimientoLabel;
    private javax.swing.JComboBox<String> grupoSanguineoCB;
    private javax.swing.JLabel grupoSanguineoLabel;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField nombreTF;
    // End of variables declaration//GEN-END:variables
}
