package lab1proyectofinal.vistas;

import java.util.List;
import javax.swing.JOptionPane;
import lab1proyectofinal.accesoADatos.BrigadaData;
import lab1proyectofinal.accesoADatos.CuartelData;
import lab1proyectofinal.accesoADatos.Utils;
import lab1proyectofinal.entidades.Brigada;
import lab1proyectofinal.entidades.Cuartel;

/**
 *
 * @author Falic
 */
public class GestionBrigada extends javax.swing.JInternalFrame {

    /**
     * SUJETO A CAMBIOS
     */
    private final CuartelData cuartelData;
    private final BrigadaData brigadaData;

    /**
     * Creates new form GestionBrigada
     */
    public GestionBrigada(CuartelData cuartelData, BrigadaData brigadaData) {
        initComponents();
        this.cuartelData = cuartelData;
        this.brigadaData = brigadaData;
    }

    private void limpiarCampos() {
        codigoTF.setText("");
        nombreTF.setText("");
        especialidadCB.setSelectedIndex(-1);
        cuartelCB.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        codigoLabel = new javax.swing.JLabel();
        codigoTF = new javax.swing.JTextField();
        nombreLabel = new javax.swing.JLabel();
        nombreTF = new javax.swing.JTextField();
        especialidadLabel = new javax.swing.JLabel();
        especialidadCB = new javax.swing.JComboBox<>();
        cuartelLabel = new javax.swing.JLabel();
        cuartelCB = new javax.swing.JComboBox<>();
        BtnBuscarCodigo = new javax.swing.JButton();
        BtnBuscarNombre = new javax.swing.JButton();
        BtnLimpiar = new javax.swing.JButton();
        BtnGuardar = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        BtnSalir = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Brigadas");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        titulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Formulario Brigada");

        codigoLabel.setText("Código:");

        nombreLabel.setText("Nombre:");

        especialidadLabel.setText("Especialidad:");

        especialidadCB.setModel(new javax.swing.DefaultComboBoxModel<>(Utils.obtenerEspecialidades()));

        cuartelLabel.setText("Cuartel:");

        BtnBuscarCodigo.setText("Buscar");
        BtnBuscarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarCodigoActionPerformed(evt);
            }
        });

        BtnBuscarNombre.setText("Buscar");
        BtnBuscarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarNombreActionPerformed(evt);
            }
        });

        BtnLimpiar.setText("Limpiar Campos");
        BtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiarActionPerformed(evt);
            }
        });

        BtnGuardar.setText("Guardar");
        BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarActionPerformed(evt);
            }
        });

        BtnEliminar.setText("Dar de Baja");
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });

        BtnSalir.setText("Salir");
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codigoLabel)
                            .addComponent(nombreLabel)
                            .addComponent(especialidadLabel)
                            .addComponent(cuartelLabel))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreTF)
                            .addComponent(especialidadCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cuartelCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(codigoTF))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnBuscarCodigo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BtnBuscarNombre, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnLimpiar)
                        .addGap(18, 18, 18)
                        .addComponent(BtnGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(BtnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(BtnSalir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoLabel)
                    .addComponent(codigoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBuscarCodigo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreLabel)
                    .addComponent(nombreTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBuscarNombre))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(especialidadLabel)
                    .addComponent(especialidadCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuartelLabel)
                    .addComponent(cuartelCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnLimpiar)
                    .addComponent(BtnGuardar)
                    .addComponent(BtnEliminar)
                    .addComponent(BtnSalir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBuscarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarCodigoActionPerformed
        // TODO: Corregir poder seleccionar items del combobox mediante codigo
        int codigo;
        try {
            codigo = Integer.parseInt(codigoTF.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Se esperaba un numero entero en Código.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Brigada brigada = brigadaData.buscarBrigada(codigo);
        if (brigada != null) {
            codigoTF.setText(Integer.toString(brigada.getCodigoBrigada()));
            nombreTF.setText(brigada.getNombreBrigada());
            especialidadCB.setSelectedItem(brigada.getEspecialidad());
            cuartelCB.setSelectedItem(brigada.getCuartel());
        } else {
            JOptionPane.showMessageDialog(this, "Brigada no encontrada.\nEs posible que haya sido dado de baja o no exista.", "Información", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnBuscarCodigoActionPerformed

    private void BtnBuscarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarNombreActionPerformed
        // TODO: Corregir poder seleccionar items del combobox mediante codigo
        String nombreStr = nombreTF.getText().trim();
        if (nombreStr.isBlank()) {
            JOptionPane.showMessageDialog(this, "Se esperaba un nombre en el campo.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Brigada brigada = brigadaData.buscarBrigadaPorNombre(nombreStr);
        if (brigada != null) {
            codigoTF.setText(Integer.toString(brigada.getCodigoBrigada()));
            nombreTF.setText(brigada.getNombreBrigada());
            especialidadCB.setSelectedItem(brigada.getEspecialidad());
            cuartelCB.setSelectedItem(brigada.getCuartel());
        } else {
            JOptionPane.showMessageDialog(this, "Brigada no encontrada.\nEs posible que haya sido dado de baja o no exista.", "Información", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnBuscarNombreActionPerformed

    private void BtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimpiarActionPerformed
        this.limpiarCampos();
    }//GEN-LAST:event_BtnLimpiarActionPerformed

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
        String codigoStr = codigoTF.getText().trim();
        String nombreStr = nombreTF.getText().trim();
        String especialidadStr = (String) especialidadCB.getSelectedItem();
        Cuartel cuartel = (Cuartel) cuartelCB.getSelectedItem();

        if (codigoStr.isBlank() || nombreStr.isBlank()
                || especialidadStr == null || cuartel == null) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int codigo;
        try {
            codigo = Integer.parseInt(codigoStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Se esperaba un numero entero en Código.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Brigada brigada = new Brigada();
        brigada.setCodigoBrigada(codigo);
        brigada.setNombreBrigada(nombreStr);
        brigada.setEspecialidad(especialidadStr);
        brigada.setDisponible(true);
        brigada.setCuartel(cuartel);
        brigada.setEstado(true);
        if (brigadaData.guardarBrigada(brigada)) {
            JOptionPane.showMessageDialog(this, "Brigada guardada.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo guardar la brigada.\nQuizás ya haya una brigada guardada con este código o nombre.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnGuardarActionPerformed

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        String codigoStr = codigoTF.getText().trim();
        String nombreStr = nombreTF.getText().trim();

        if (codigoStr.isBlank() && nombreStr.isBlank()) {
            JOptionPane.showMessageDialog(this, "Debe especificar código o nombre de la brigada a eliminar.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int codigo = -1;
        try {
            codigo = Integer.parseInt(codigoStr);
        } catch (NumberFormatException e) {
        }

        boolean resultado = false;
        if (codigo != -1) {
            resultado = brigadaData.eliminarBrigada(codigo);
        } else {
            resultado = brigadaData.eliminarBrigadaPorNombre(nombreStr);
        }
        if (resultado) {
            this.limpiarCampos();
            JOptionPane.showMessageDialog(this, "Brigada dada de baja.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo dar de baja la brigada.\nQuizás la brigada ya haya sido dada de baja o no exista.", "Información", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_BtnEliminarActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        this.hide();
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        cuartelCB.removeAllItems();

        List<Cuartel> cuarteles = cuartelData.listarCuarteles();
        if (!cuarteles.isEmpty()) {
            for (Cuartel cuartel : cuarteles) {
                cuartelCB.addItem(cuartel);
            }
            cuartelCB.setEnabled(true);
            BtnGuardar.setEnabled(true);
        } else {
            cuartelCB.setEnabled(false);
            BtnGuardar.setEnabled(false);
        }

        this.limpiarCampos();
    }//GEN-LAST:event_formInternalFrameActivated


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscarCodigo;
    private javax.swing.JButton BtnBuscarNombre;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JButton BtnLimpiar;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JLabel codigoLabel;
    private javax.swing.JTextField codigoTF;
    private javax.swing.JComboBox<Cuartel> cuartelCB;
    private javax.swing.JLabel cuartelLabel;
    private javax.swing.JComboBox<String> especialidadCB;
    private javax.swing.JLabel especialidadLabel;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField nombreTF;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
