/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package lab1proyectofinal.vistas;

import lab1proyectofinal.accesoADatos.BomberoData;

/**
 *
 * @author Nahue
 */
public class GestionBombero extends javax.swing.JInternalFrame {

    /**
     * Creates new form GestionBombero
     */
    BomberoData BomberoData;
    
    public GestionBombero(BomberoData bomberoData) {
        initComponents();
        this.BomberoData=BomberoData;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        IdjLabel = new javax.swing.JLabel();
        DnijLabel = new javax.swing.JLabel();
        NombrejLabel = new javax.swing.JLabel();
        GrupojLabel = new javax.swing.JLabel();
        FechajLabel = new javax.swing.JLabel();
        CelularjLabel = new javax.swing.JLabel();
        CodigojLabel = new javax.swing.JLabel();
        IdjTextField = new javax.swing.JTextField();
        DnijTextField = new javax.swing.JTextField();
        NombrejTextField = new javax.swing.JTextField();
        GrupojTextField = new javax.swing.JTextField();
        FechajTextField = new javax.swing.JTextField();
        CelularjTextField = new javax.swing.JTextField();
        IDjButton = new javax.swing.JButton();
        DNIjButton = new javax.swing.JButton();
        LimpiarjButton = new javax.swing.JButton();
        GuardarjButton = new javax.swing.JButton();
        SalirjButton = new javax.swing.JButton();
        EstadojLabel = new javax.swing.JLabel();
        CodigojTextField = new javax.swing.JTextField();

        jLabel1.setText("Gestion de bomberos");

        IdjLabel.setText("ID Bombero:");

        DnijLabel.setText("DNI:");

        NombrejLabel.setText("Nombres:");

        GrupojLabel.setText("Grupo Sanguinio:");

        FechajLabel.setText("Fecha de Nacimiento:");

        CelularjLabel.setText("Celular:");

        CodigojLabel.setText("Codigo de Brigada:");

        GrupojTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GrupojTextFieldActionPerformed(evt);
            }
        });

        IDjButton.setText("Buscar");

        DNIjButton.setText("Buscar");

        LimpiarjButton.setText("Limpiar Campos");

        GuardarjButton.setText("Guardar");

        SalirjButton.setText("Salir");

        EstadojLabel.setText("Estado:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(IdjLabel)
                                    .addComponent(DnijLabel)
                                    .addComponent(NombrejLabel)
                                    .addComponent(GrupojLabel)
                                    .addComponent(FechajLabel)
                                    .addComponent(CelularjLabel)
                                    .addComponent(CodigojLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(IdjTextField)
                                    .addComponent(DnijTextField)
                                    .addComponent(NombrejTextField)
                                    .addComponent(GrupojTextField)
                                    .addComponent(CelularjTextField)
                                    .addComponent(FechajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CodigojTextField))
                                .addGap(34, 34, 34))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EstadojLabel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LimpiarjButton)
                                        .addGap(39, 39, 39)
                                        .addComponent(GuardarjButton)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SalirjButton)
                            .addComponent(IDjButton)
                            .addComponent(DNIjButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel1)))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdjLabel)
                    .addComponent(IdjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDjButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DnijLabel)
                    .addComponent(DnijTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DNIjButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombrejLabel)
                    .addComponent(NombrejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GrupojLabel)
                    .addComponent(GrupojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FechajLabel)
                    .addComponent(FechajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CelularjLabel)
                    .addComponent(CelularjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CodigojLabel)
                    .addComponent(CodigojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(EstadojLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LimpiarjButton)
                    .addComponent(GuardarjButton)
                    .addComponent(SalirjButton))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GrupojTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GrupojTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GrupojTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CelularjLabel;
    private javax.swing.JTextField CelularjTextField;
    private javax.swing.JLabel CodigojLabel;
    private javax.swing.JTextField CodigojTextField;
    private javax.swing.JButton DNIjButton;
    private javax.swing.JLabel DnijLabel;
    private javax.swing.JTextField DnijTextField;
    private javax.swing.JLabel EstadojLabel;
    private javax.swing.JLabel FechajLabel;
    private javax.swing.JTextField FechajTextField;
    private javax.swing.JLabel GrupojLabel;
    private javax.swing.JTextField GrupojTextField;
    private javax.swing.JButton GuardarjButton;
    private javax.swing.JButton IDjButton;
    private javax.swing.JLabel IdjLabel;
    private javax.swing.JTextField IdjTextField;
    private javax.swing.JButton LimpiarjButton;
    private javax.swing.JLabel NombrejLabel;
    private javax.swing.JTextField NombrejTextField;
    private javax.swing.JButton SalirjButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
