package lab1proyectofinal.vistas;

import java.util.List;
import javax.swing.JOptionPane;
import lab1proyectofinal.accesoADatos.BrigadaData;
import lab1proyectofinal.accesoADatos.CuartelData;
import lab1proyectofinal.accesoADatos.Utils;
import lab1proyectofinal.entidades.Brigada;
import lab1proyectofinal.entidades.Cuartel;

/**
 *
 * @author Falic
 */
public class GestionBrigada extends javax.swing.JInternalFrame {

    /**
     * SUJETO A CAMBIOS
     */
    private final CuartelData cuartelData;
    private final BrigadaData brigadaData;

    /**
     * Creates new form GestionBrigada
     */
    public GestionBrigada(CuartelData cuartelData, BrigadaData brigadaData) {
        initComponents();
        this.cuartelData = cuartelData;
        this.brigadaData = brigadaData;
    }

    private void limpiarCampos() {
        brigadaCB.setSelectedIndex(-1);
        nombreTF.setText("");
        especialidadCB.setSelectedIndex(-1);
        cuartelCB.setSelectedIndex(-1);
        disponibleChB.setSelected(false);
        setFieldsEnabled(false);
    }

    private void setFieldsEnabled(boolean flag) {
        nombreTF.setEnabled(flag);
        especialidadCB.setEnabled(flag);
        cuartelCB.setEnabled(flag);
        disponibleChB.setEnabled(flag);
        BtnGuardar.setEnabled(flag);
        BtnEditar.setEnabled(!flag);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        brigadaLabel = new javax.swing.JLabel();
        brigadaCB = new javax.swing.JComboBox<>();
        nombreLabel = new javax.swing.JLabel();
        nombreTF = new javax.swing.JTextField();
        especialidadLabel = new javax.swing.JLabel();
        especialidadCB = new javax.swing.JComboBox<>();
        cuartelLabel = new javax.swing.JLabel();
        cuartelCB = new javax.swing.JComboBox<>();
        disponibleLabel = new javax.swing.JLabel();
        disponibleChB = new javax.swing.JCheckBox();
        BtnEditar = new javax.swing.JButton();
        BtnGuardar = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        BtnSalir = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Gestion Brigada");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        brigadaLabel.setText("Brigada:");

        brigadaCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brigadaCBActionPerformed(evt);
            }
        });

        nombreLabel.setText("Nombre:");

        especialidadLabel.setText("Especialidad:");

        especialidadCB.setModel(new javax.swing.DefaultComboBoxModel<>(Utils.obtenerEspecialidades()));

        cuartelLabel.setText("Cuartel:");

        disponibleLabel.setText("Disponible:");

        BtnEditar.setText("Editar");
        BtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditarActionPerformed(evt);
            }
        });

        BtnGuardar.setText("Guardar");
        BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarActionPerformed(evt);
            }
        });

        BtnEliminar.setText("Dar de Baja");
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });

        BtnSalir.setText("Salir");
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnEditar)
                        .addGap(18, 18, 18)
                        .addComponent(BtnGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(BtnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(BtnSalir))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(especialidadLabel)
                            .addComponent(cuartelLabel)
                            .addComponent(disponibleLabel)
                            .addComponent(nombreLabel)
                            .addComponent(brigadaLabel))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(disponibleChB)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(nombreTF)
                            .addComponent(brigadaCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cuartelCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(especialidadCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brigadaCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brigadaLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreLabel)
                    .addComponent(nombreTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(especialidadLabel)
                    .addComponent(especialidadCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuartelLabel)
                    .addComponent(cuartelCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(disponibleLabel)
                    .addComponent(disponibleChB))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnGuardar)
                    .addComponent(BtnEliminar)
                    .addComponent(BtnSalir)
                    .addComponent(BtnEditar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        brigadaCB.removeAllItems();
        List<Brigada> brigadas = brigadaData.listarBrigadas();
        if (!brigadas.isEmpty()) {
            for (Brigada brigada : brigadas) {
                brigadaCB.addItem(brigada);
                cuartelCB.addItem(brigada.getCuartel());
            }
            brigadaCB.setEnabled(true);
        } else {
            brigadaCB.setEnabled(false);
        }

        limpiarCampos();
        setFieldsEnabled(false);
    }//GEN-LAST:event_formInternalFrameActivated

    private void brigadaCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brigadaCBActionPerformed
        Brigada brigadaSeleccionada = (Brigada) brigadaCB.getSelectedItem();
        if (brigadaSeleccionada != null) {
            setFieldsEnabled(false);
            nombreTF.setText(brigadaSeleccionada.getNombreBrigada());
            especialidadCB.setSelectedItem(brigadaSeleccionada.getEspecialidad());
            cuartelCB.setSelectedItem(brigadaSeleccionada.getCuartel());
            disponibleChB.setSelected(brigadaSeleccionada.isDisponible());
        }
    }//GEN-LAST:event_brigadaCBActionPerformed

    private void BtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditarActionPerformed
        Brigada brigadaSeleccionada = (Brigada) brigadaCB.getSelectedItem();
        if (brigadaSeleccionada != null) {
            setFieldsEnabled(true);
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione primero una brigada a editar.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnEditarActionPerformed

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
        Brigada brigadaSeleccionada = (Brigada) brigadaCB.getSelectedItem();
        if (brigadaSeleccionada == null) {
            JOptionPane.showMessageDialog(this, "Seleccione primero una brigada a editar.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String nombreStr = nombreTF.getText().trim();
        String especialidadStr = (String) especialidadCB.getSelectedItem();
        Cuartel cuartel = (Cuartel) cuartelCB.getSelectedItem();
        boolean disponible = disponibleChB.isSelected();

        if (nombreStr.isBlank() || especialidadStr == null || cuartel == null) {
            JOptionPane.showMessageDialog(this, "No puede haber campos vacios.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Brigada brigada = new Brigada(nombreStr, especialidadStr, disponible, cuartel);
        brigada.setCodigoBrigada(brigadaSeleccionada.getCodigoBrigada());
        if (brigadaData.modificarBrigada(brigada)) {
            brigadaSeleccionada.setNombreBrigada(nombreStr);
            brigadaSeleccionada.setEspecialidad(especialidadStr);
            brigadaSeleccionada.setCuartel(cuartel);
            brigadaSeleccionada.setDisponible(disponible);
            JOptionPane.showMessageDialog(this, "Brigada modificada.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo guardar la edición.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnGuardarActionPerformed

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        Brigada brigadaSeleccionada = (Brigada) brigadaCB.getSelectedItem();
        if (brigadaSeleccionada == null) {
            JOptionPane.showMessageDialog(this, "Seleccione primero un cuartel a eliminar.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int option = JOptionPane.showConfirmDialog(this, "¿Está seguro de que desea eliminar esta brigada?", "Confirmar eliminacion", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (option == JOptionPane.YES_OPTION) {
            if (brigadaData.eliminarBrigada(brigadaSeleccionada.getCodigoBrigada())){
                brigadaCB.removeItem(brigadaSeleccionada);
                JOptionPane.showMessageDialog(this, "Cuartel eliminado.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo eliminar.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_BtnEliminarActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        this.hide();
    }//GEN-LAST:event_BtnSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEditar;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JComboBox<Brigada> brigadaCB;
    private javax.swing.JLabel brigadaLabel;
    private javax.swing.JComboBox<Cuartel> cuartelCB;
    private javax.swing.JLabel cuartelLabel;
    private javax.swing.JCheckBox disponibleChB;
    private javax.swing.JLabel disponibleLabel;
    private javax.swing.JComboBox<String> especialidadCB;
    private javax.swing.JLabel especialidadLabel;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField nombreTF;
    // End of variables declaration//GEN-END:variables
}
