/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package lab1proyectofinal.vistas;

import java.awt.Color;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import lab1proyectofinal.accesoADatos.BrigadaData;
import lab1proyectofinal.entidades.*;
import lab1proyectofinal.accesoADatos.Utils;

/**
 *
 * @author nahue
 */
public class ListadosPorBrigada extends javax.swing.JInternalFrame {

    private final BrigadaData brigadaData;
    private List<Brigada> brigadas;
    private List<Bombero> bomberos;
    private Brigada brigada;
    private int filaSeleccionada;
    private DefaultTableModel modeloTablaBrigadas = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int i, int i1) {
            return false;
        }
    };
    private DefaultTableModel modeloTablaBomberos = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int i, int i1) {
            return false;
        }
    };

    public ListadosPorBrigada(BrigadaData brigadaData) {
        initComponents();
        this.brigadaData = brigadaData;
        armarCabeceras();
    }

    private void armarCabeceras() {
        jTableTodasLasBrigadas.getTableHeader().setFont(Utils.fuenteNegrita);
        jTableBomberosDeBrigada.getTableHeader().setFont(Utils.fuenteNegrita);
        modeloTablaBrigadas.addColumn("Nombre");
        modeloTablaBrigadas.addColumn("Especialidad");
        modeloTablaBrigadas.addColumn("Disponible");
        modeloTablaBrigadas.addColumn("Cuartel");
        modeloTablaBomberos.addColumn("DNI");
        modeloTablaBomberos.addColumn("Nombre completo");
        modeloTablaBomberos.addColumn("Grupo sanguíneo");
        modeloTablaBomberos.addColumn("Nro de celular");
        jTableTodasLasBrigadas.setModel(modeloTablaBrigadas);
        jTableTodasLasBrigadas.getColumnModel().getColumn(0).setPreferredWidth(70);
        jTableTodasLasBrigadas.getColumnModel().getColumn(1).setPreferredWidth(250);
        jTableTodasLasBrigadas.getColumnModel().getColumn(2).setPreferredWidth(5);
        jTableBomberosDeBrigada.setModel(modeloTablaBomberos);
        jTableBomberosDeBrigada.getColumnModel().getColumn(0).setPreferredWidth(20);
        jTableBomberosDeBrigada.getColumnModel().getColumn(1).setPreferredWidth(180);
        jTableBomberosDeBrigada.getColumnModel().getColumn(2).setPreferredWidth(20);
    }

    private void cargarDatosTablaBrigadas() {
        brigadas = brigadaData.listarBrigadas();
        modeloTablaBrigadas.setRowCount(0);
        if (brigadas.isEmpty()) {
            jLabelMensajeTablaBrigadas.setForeground(Color.BLACK);
            jLabelMensajeTablaBrigadas.setText("No hay ninguna brigada registrada.");
        } else {
            for (Brigada bri : brigadas) {
                modeloTablaBrigadas.addRow(new Object[]{bri.getNombreBrigada(),
                    bri.getEspecialidad(), bri.isDisponible() ? "Si" : "No ",
                    bri.getCuartel().getNombreCuartel()});
            }
            jLabelMensajeTablaBrigadas.setText("<html>Seleccione una brigada de la tabla haciendo "
                    + "click en su fila para ver los bomberos vinculados a la misma.</html>");
        }
    }

    private void cargarDatosTablaBomberos(Brigada brigada) {
        bomberos = brigadaData.listarBomberosDeBrigada(brigada);
        modeloTablaBomberos.setRowCount(0);
        if (bomberos.isEmpty()) {
            jLabelMensajeTablaBomberos.setForeground(Color.BLACK);
            jLabelMensajeTablaBomberos.setText("No hay bomberos registrados en la brigada \""
                    + brigada.getNombreBrigada() + "\".");
        } else {
            for (Bombero bombero : bomberos) {
                modeloTablaBomberos.addRow(new Object[]{bombero.getDni(),
                    bombero.getNombreCompleto(), bombero.getGrupoSanguineo(),
                    bombero.getCelular()});
            }
            jLabelMensajeTablaBomberos.setText("");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneBomberosDelCuartel = new javax.swing.JScrollPane();
        jTableBomberosDeBrigada = new javax.swing.JTable();
        jLabelBomberosBrigada = new javax.swing.JLabel();
        jScrollPaneBrigadasDelCuartel = new javax.swing.JScrollPane();
        jTableTodasLasBrigadas = new javax.swing.JTable();
        jLabelTodasLasBrigadas = new javax.swing.JLabel();
        jLabelTituloPrincipal = new javax.swing.JLabel();
        jLabelMensajeTablaBomberos = new javax.swing.JLabel();
        jLabelMensajeTablaBrigadas = new javax.swing.JLabel();
        jButtonSalir = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1022, 718));
        setRequestFocusEnabled(false);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameDeactivated(evt);
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableBomberosDeBrigada.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTableBomberosDeBrigada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableBomberosDeBrigada.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        jTableBomberosDeBrigada.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableBomberosDeBrigada.getTableHeader().setResizingAllowed(false);
        jTableBomberosDeBrigada.getTableHeader().setReorderingAllowed(false);
        jScrollPaneBomberosDelCuartel.setViewportView(jTableBomberosDeBrigada);

        getContentPane().add(jScrollPaneBomberosDelCuartel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 800, 210));

        jLabelBomberosBrigada.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelBomberosBrigada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBomberosBrigada.setText("Bomberos de la brigada seleccionada");
        getContentPane().add(jLabelBomberosBrigada, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 800, -1));

        jTableTodasLasBrigadas.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTableTodasLasBrigadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableTodasLasBrigadas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        jTableTodasLasBrigadas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableTodasLasBrigadas.getTableHeader().setResizingAllowed(false);
        jTableTodasLasBrigadas.getTableHeader().setReorderingAllowed(false);
        jTableTodasLasBrigadas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTableTodasLasBrigadasMouseReleased(evt);
            }
        });
        jScrollPaneBrigadasDelCuartel.setViewportView(jTableTodasLasBrigadas);

        getContentPane().add(jScrollPaneBrigadasDelCuartel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 800, 210));

        jLabelTodasLasBrigadas.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelTodasLasBrigadas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTodasLasBrigadas.setText("Todas las brigadas");
        getContentPane().add(jLabelTodasLasBrigadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 800, -1));

        jLabelTituloPrincipal.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelTituloPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloPrincipal.setText("Listados por brigada");
        getContentPane().add(jLabelTituloPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 800, -1));

        jLabelMensajeTablaBomberos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        getContentPane().add(jLabelMensajeTablaBomberos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 790, 20));

        jLabelMensajeTablaBrigadas.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        getContentPane().add(jLabelMensajeTablaBrigadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 780, 20));

        jButtonSalir.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 620, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        cargarDatosTablaBrigadas();
    }//GEN-LAST:event_formInternalFrameActivated

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        this.hide();
        jTableTodasLasBrigadas.removeRowSelectionInterval(0, jTableTodasLasBrigadas.getRowCount()
                - 1);
        modeloTablaBomberos.setRowCount(0);
        jLabelMensajeTablaBomberos.setForeground(Color.BLACK);
        jLabelMensajeTablaBomberos.setText("");
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void formInternalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameDeactivated
        jTableTodasLasBrigadas.removeRowSelectionInterval(0, jTableTodasLasBrigadas.getRowCount()
                - 1);
        modeloTablaBomberos.setRowCount(0);
        jLabelMensajeTablaBomberos.setForeground(Color.BLACK);
        jLabelMensajeTablaBomberos.setText("");
    }//GEN-LAST:event_formInternalFrameDeactivated

    private void jTableTodasLasBrigadasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTodasLasBrigadasMouseReleased
        filaSeleccionada = jTableTodasLasBrigadas.getSelectedRow();
        brigada = brigadaData.buscarBrigadaPorNombre(
                (String) jTableTodasLasBrigadas.getValueAt(filaSeleccionada, 0));
        cargarDatosTablaBomberos(brigada);
    }//GEN-LAST:event_jTableTodasLasBrigadasMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelBomberosBrigada;
    private javax.swing.JLabel jLabelMensajeTablaBomberos;
    private javax.swing.JLabel jLabelMensajeTablaBrigadas;
    private javax.swing.JLabel jLabelTituloPrincipal;
    private javax.swing.JLabel jLabelTodasLasBrigadas;
    private javax.swing.JScrollPane jScrollPaneBomberosDelCuartel;
    private javax.swing.JScrollPane jScrollPaneBrigadasDelCuartel;
    private javax.swing.JTable jTableBomberosDeBrigada;
    private javax.swing.JTable jTableTodasLasBrigadas;
    // End of variables declaration//GEN-END:variables
}
