/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package lab1proyectofinal.vistas;

import java.awt.Color;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import lab1proyectofinal.accesoADatos.BrigadaData;
import lab1proyectofinal.entidades.*;
import lab1proyectofinal.accesoADatos.Utils;

/**
 *
 * @author nahue
 */
public class ListadosPorBrigada extends javax.swing.JInternalFrame {

    private final BrigadaData brigadaData;
    private List<Brigada> listaBrigada;
    private List<Bombero> listaBombero;
    private Brigada brigada;
    private int filaSelec;
    private DefaultTableModel modeloTablaBrigadas = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int i, int i1) {
            return false;
        }
    };
    private DefaultTableModel modeloTablaBomberos = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int i, int i1) {
            return false;
        }
    };

    public ListadosPorBrigada(BrigadaData brigadaData) {
        initComponents();
        this.brigadaData = brigadaData;
        configurarTablas();
    }

    private void configurarTablas() {
        jTaTodasLasBrigadas.getTableHeader().setFont(Utils.fuenteNegrita);
        jTaBomberosDeBrigada.getTableHeader().setFont(Utils.fuenteNegrita);
        modeloTablaBrigadas.addColumn("Nombre");
        modeloTablaBrigadas.addColumn("Especialidad");
        modeloTablaBrigadas.addColumn("En servicio");
        modeloTablaBrigadas.addColumn("Cuartel");
        modeloTablaBomberos.addColumn("DNI");
        modeloTablaBomberos.addColumn("Nombre completo");
        modeloTablaBomberos.addColumn("Grupo sanguíneo");
        modeloTablaBomberos.addColumn("Nro de celular");
        jTaTodasLasBrigadas.setModel(modeloTablaBrigadas);
        jTaTodasLasBrigadas.getColumnModel().getColumn(0).setPreferredWidth(70);
        jTaTodasLasBrigadas.getColumnModel().getColumn(1).setPreferredWidth(250);
        jTaTodasLasBrigadas.getColumnModel().getColumn(2).setPreferredWidth(5);
        jTaBomberosDeBrigada.setModel(modeloTablaBomberos);
        jTaBomberosDeBrigada.getColumnModel().getColumn(0).setPreferredWidth(20);
        jTaBomberosDeBrigada.getColumnModel().getColumn(1).setPreferredWidth(180);
        jTaBomberosDeBrigada.getColumnModel().getColumn(2).setPreferredWidth(20);

        jTaTodasLasBrigadas.setRowHeight(23);
        jTaBomberosDeBrigada.setRowHeight(23);

        TableRowSorter<TableModel> sorter = new TableRowSorter<>(modeloTablaBrigadas);        
        sorter.toggleSortOrder(0);
        jTaTodasLasBrigadas.setRowSorter(sorter);
    }

    private void cargarDatosTablaBrigadas() {
        listaBrigada = brigadaData.listarBrigadas();
        modeloTablaBrigadas.setRowCount(0);
        if (listaBrigada.isEmpty()) {
            jLabMensajeTablaBrigadas.setForeground(Color.BLACK);
            jLabMensajeTablaBrigadas.setText("No hay ninguna brigada registrada.");
        } else {
            for (Brigada bri : listaBrigada) {
                modeloTablaBrigadas.addRow(new Object[]{bri.getNombreBrigada(),
                    bri.getEspecialidad(), bri.isEnServicio() ? "Si" : "No ",
                    bri.getCuartel().getNombreCuartel()});
            }
            jLabMensajeTablaBrigadas.setText("<html>Seleccione una brigada de la tabla haciendo "
                    + "click en su fila para ver los bomberos vinculados a la misma. También puede "
                    + "hacer click en las columnas de la cabecera para ordenar las filas</html>");
        }
    }

    private void cargarDatosTablaBomberos(Brigada brigada) {
        listaBombero = brigadaData.listarBomberosDeBrigada(brigada);
        modeloTablaBomberos.setRowCount(0);
        if (listaBombero.isEmpty()) {
            jLabMensajeTablaBomberos.setForeground(Color.BLACK);
            jLabMensajeTablaBomberos.setText("No hay bomberos registrados en la brigada \""
                    + brigada.getNombreBrigada() + "\".");
        } else {
            for (Bombero bombero : listaBombero) {
                modeloTablaBomberos.addRow(new Object[]{bombero.getDni(),
                    bombero.getNombreCompleto(), bombero.getGrupoSanguineo(),
                    bombero.getCelular()});
            }
            jLabMensajeTablaBomberos.setText("");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScPBomberosDeBrigada = new javax.swing.JScrollPane();
        jTaBomberosDeBrigada = new javax.swing.JTable();
        jLabBomberosBrigada = new javax.swing.JLabel();
        jScPBrigadas = new javax.swing.JScrollPane();
        jTaTodasLasBrigadas = new javax.swing.JTable();
        jLabTodasLasBrigadas = new javax.swing.JLabel();
        jLabListadosPorBrigada = new javax.swing.JLabel();
        jLabMensajeTablaBomberos = new javax.swing.JLabel();
        jLabMensajeTablaBrigadas = new javax.swing.JLabel();
        jBSalir = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1022, 740));
        setRequestFocusEnabled(false);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameDeactivated(evt);
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTaBomberosDeBrigada.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTaBomberosDeBrigada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTaBomberosDeBrigada.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        jTaBomberosDeBrigada.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTaBomberosDeBrigada.getTableHeader().setResizingAllowed(false);
        jTaBomberosDeBrigada.getTableHeader().setReorderingAllowed(false);
        jScPBomberosDeBrigada.setViewportView(jTaBomberosDeBrigada);

        getContentPane().add(jScPBomberosDeBrigada, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 800, 210));

        jLabBomberosBrigada.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabBomberosBrigada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabBomberosBrigada.setText("Bomberos de la brigada seleccionada");
        getContentPane().add(jLabBomberosBrigada, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 800, -1));

        jTaTodasLasBrigadas.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTaTodasLasBrigadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTaTodasLasBrigadas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        jTaTodasLasBrigadas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTaTodasLasBrigadas.getTableHeader().setResizingAllowed(false);
        jTaTodasLasBrigadas.getTableHeader().setReorderingAllowed(false);
        jTaTodasLasBrigadas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTaTodasLasBrigadasMouseReleased(evt);
            }
        });
        jScPBrigadas.setViewportView(jTaTodasLasBrigadas);

        getContentPane().add(jScPBrigadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 800, 210));

        jLabTodasLasBrigadas.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabTodasLasBrigadas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabTodasLasBrigadas.setText("Todas las brigadas");
        getContentPane().add(jLabTodasLasBrigadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 800, -1));

        jLabListadosPorBrigada.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabListadosPorBrigada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabListadosPorBrigada.setText("Listados por brigada");
        getContentPane().add(jLabListadosPorBrigada, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 800, -1));

        jLabMensajeTablaBomberos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        getContentPane().add(jLabMensajeTablaBomberos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 790, 20));

        jLabMensajeTablaBrigadas.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        getContentPane().add(jLabMensajeTablaBrigadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 780, 46));

        jBSalir.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jBSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 620, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        cargarDatosTablaBrigadas();
    }//GEN-LAST:event_formInternalFrameActivated

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        this.hide();
        if (jTaTodasLasBrigadas.getRowCount() > 0) {
            jTaTodasLasBrigadas.removeRowSelectionInterval(0,
                    jTaTodasLasBrigadas.getRowCount() - 1);
        }
        modeloTablaBomberos.setRowCount(0);
        jLabMensajeTablaBomberos.setForeground(Color.BLACK);
        jLabMensajeTablaBomberos.setText("");
    }//GEN-LAST:event_jBSalirActionPerformed

    private void formInternalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameDeactivated
        if (jTaTodasLasBrigadas.getRowCount() > 0) {
            jTaTodasLasBrigadas.removeRowSelectionInterval(0,
                    jTaTodasLasBrigadas.getRowCount() - 1);
        }
        modeloTablaBomberos.setRowCount(0);
        jLabMensajeTablaBomberos.setForeground(Color.BLACK);
        jLabMensajeTablaBomberos.setText("");
    }//GEN-LAST:event_formInternalFrameDeactivated

    private void jTaTodasLasBrigadasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTaTodasLasBrigadasMouseReleased
        filaSelec = jTaTodasLasBrigadas.getSelectedRow();
        brigada = brigadaData.buscarBrigadaPorNombre(
                (String) jTaTodasLasBrigadas.getValueAt(filaSelec, 0));
        cargarDatosTablaBomberos(brigada);
    }//GEN-LAST:event_jTaTodasLasBrigadasMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBSalir;
    private javax.swing.JLabel jLabBomberosBrigada;
    private javax.swing.JLabel jLabListadosPorBrigada;
    private javax.swing.JLabel jLabMensajeTablaBomberos;
    private javax.swing.JLabel jLabMensajeTablaBrigadas;
    private javax.swing.JLabel jLabTodasLasBrigadas;
    private javax.swing.JScrollPane jScPBomberosDeBrigada;
    private javax.swing.JScrollPane jScPBrigadas;
    private javax.swing.JTable jTaBomberosDeBrigada;
    private javax.swing.JTable jTaTodasLasBrigadas;
    // End of variables declaration//GEN-END:variables
}
