/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package lab1proyectofinal.vistas;

import java.awt.Color;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import lab1proyectofinal.accesoADatos.*;
import lab1proyectofinal.entidades.*;

/**
 *
 * @author nahue
 */
public class ListadoDeBomberos extends javax.swing.JInternalFrame {

    private final BomberoData bomberoData;
    private List<Bombero> listaBombero;
    private Bombero bombero;
    private int filaSelec;
    private DefaultTableModel modeloJTaBomberos = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int i, int i1) {
            return false;
        }
    };

    public ListadoDeBomberos(BomberoData bomberoData) {
        initComponents();
        this.bomberoData = bomberoData;
        configurarTabla();
    }

    private void configurarTabla() {
        jTaBomberos.getTableHeader().setFont(Utils.fuenteNegrita);
        modeloJTaBomberos.addColumn("DNI");
        modeloJTaBomberos.addColumn("Nombre completo");
        modeloJTaBomberos.addColumn("Grupo sanguíneo");
        modeloJTaBomberos.addColumn("Nro de celular");
        modeloJTaBomberos.addColumn("Brigada");
        jTaBomberos.setModel(modeloJTaBomberos);
        jTaBomberos.getColumnModel().getColumn(0).setPreferredWidth(5);
        jTaBomberos.getColumnModel().getColumn(1).setPreferredWidth(125);
        jTaBomberos.getColumnModel().getColumn(2).setPreferredWidth(5);
        jTaBomberos.getColumnModel().getColumn(3).setPreferredWidth(5);

        jTaBomberos.setRowHeight(23);
    }

    private void cargarDatosTablaBomberos() {
        listaBombero = bomberoData.listarBomberos();
        modeloJTaBomberos.setRowCount(0);
        if (listaBombero.isEmpty()) {
            jLabMensajeJTaBomberos.setForeground(Color.BLACK);
            jLabMensajeJTaBomberos.setText("No hay bomberos registrados.");
        } else {
            for (Bombero bombero : listaBombero) {
                modeloJTaBomberos.addRow(new Object[]{bombero.getDni(),
                    bombero.getNombreCompleto(), bombero.getGrupoSanguineo(), bombero.getCelular(),
                    bombero.getBrigada().getNombreBrigada()});
            }
            jLabMensajeJTaBomberos.setText("");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScPBomberos = new javax.swing.JScrollPane();
        jTaBomberos = new javax.swing.JTable();
        jLabTodosLosBomberos = new javax.swing.JLabel();
        jLabListadoBomberos = new javax.swing.JLabel();
        jLabMensajeJTaBomberos = new javax.swing.JLabel();
        jBSalir = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1097, 722));
        setRequestFocusEnabled(false);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameDeactivated(evt);
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTaBomberos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTaBomberos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTaBomberos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        jTaBomberos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTaBomberos.getTableHeader().setResizingAllowed(false);
        jTaBomberos.getTableHeader().setReorderingAllowed(false);
        jScPBomberos.setViewportView(jTaBomberos);

        getContentPane().add(jScPBomberos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 940, 470));

        jLabTodosLosBomberos.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabTodosLosBomberos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabTodosLosBomberos.setText("Todos los bomberos");
        getContentPane().add(jLabTodosLosBomberos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 940, -1));

        jLabListadoBomberos.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabListadoBomberos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabListadoBomberos.setText("Listado de bomberos");
        getContentPane().add(jLabListadoBomberos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 940, -1));

        jLabMensajeJTaBomberos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        getContentPane().add(jLabMensajeJTaBomberos, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 930, 20));

        jBSalir.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jBSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 640, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        cargarDatosTablaBomberos();
    }//GEN-LAST:event_formInternalFrameActivated

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        this.hide();
        if (jTaBomberos.getRowCount() > 0) {
            jTaBomberos.removeRowSelectionInterval(0, jTaBomberos.getRowCount() - 1);
        }
        modeloJTaBomberos.setRowCount(0);
        jLabMensajeJTaBomberos.setText("");
    }//GEN-LAST:event_jBSalirActionPerformed

    private void formInternalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameDeactivated
        if (jTaBomberos.getRowCount() > 0) {
            jTaBomberos.removeRowSelectionInterval(0, jTaBomberos.getRowCount() - 1);
        }
        modeloJTaBomberos.setRowCount(0);
        jLabMensajeJTaBomberos.setText("");
    }//GEN-LAST:event_formInternalFrameDeactivated


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBSalir;
    private javax.swing.JLabel jLabListadoBomberos;
    private javax.swing.JLabel jLabMensajeJTaBomberos;
    private javax.swing.JLabel jLabTodosLosBomberos;
    private javax.swing.JScrollPane jScPBomberos;
    private javax.swing.JTable jTaBomberos;
    // End of variables declaration//GEN-END:variables
}
